services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-bdd}
    ports:
      - 5432:5432
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8098:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_DB=${POSTGRES_DB:-bdd}
      - ADMINER_DEFAULT_USER=${POSTGRES_USER:-postgres}
      - ADMINER_DEFAULT_PASSWORD=${POSTGRES_PASSWORD:-postgres}
