CREATE TABLE REGION(
  ID_REGION INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  NOMBRE VARCHAR(200),
  CODIGO VARCHAR(10),
  VIGENTE CHAR(1)
);

CREATE TABLE COMUNA(
  ID_COMUNA INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  ID_REGION INTEGER NOT NULL,
  NOMBRE VARCHAR(200),
  CODIGO VARCHAR(10),
  VIGENTE CHAR(1)
);

ALTER TABLE COMUNA
ADD FOREIGN KEY (ID_REGION) 
REFERENCES REGION (ID_REGION) 
ON DELETE CASCADE ON UPDATE RESTRICT;